version: "3.9"
services:

  redis:
    image: redis
    container_name: redis
    ports:
     - "6379:6379"
    command:  redis-server --save 60 1 --loglevel warning 
    restart: always

  backend:
    build: .
    container_name: backend
    command: gunicorn -c /app/gunicorn.conf.py core.wsgi:application
    volumes:
      - ./core:/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis

  worker-celery:
    build: .
    volumes:
      - ./core:/app
    command: celery -A core worker -l INFO
    depends_on:
      - backend
      - redis

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - redis
      - backend
    