version: "3.9"
services:

  redis:
    image: redis
    container_name: redis
    ports:
     - "6379:6379"
    command:  redis-server --save 60 1 --loglevel warning 
    restart: always

  backend:
    build: .
    container_name: backend
    command: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis

  worker-celery:
    build: .
    volumes:
      - ./core:/app
    command: celery -A core worker -l INFO
    depends_on:
      - backend
      - redis
